# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-05 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeSense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
