# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-05 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20170305_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('created_at',)},
        ),
    ]
