# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-05 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reMind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='first_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='last_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='nickname',
            field=models.CharField(default='My Home', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
